### ISSUE TITLE
[BUG] Messages sent to BOT in DM get answered in #general

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/botkit-starter-rocketchat#1]
Currently all replies goes to the room configured in  `.env` ,  even if I send message to bot via DM.

**Comment by Sing-Li** [comment]
@arthurTemporim  pls lmk when there is a fix to test.  Thanks.

**Comment by arthurTemporim** [comment]
To solve this issue I upgrade the way that the bot listen to messages using the [driver.respondToMessages(callback, options)](https://github.com/RocketChat/Rocket.Chat.js.SDK) from the SDK.js.
Now the bot can answer direct messages, channels and edited messages too. The new version is already published and you can check it at [npm](https://www.npmjs.com/package/botkit-rocketchat-connector) or just updating your [starter](https://github.com/RocketChat/botkit-starter-rocketchat).
:smile:

**Comment by Sing-Li** [comment]
Awesome.  @arthurTemporim   I have verified the fix.  Next time, please ask the community member who post the bug to verify the fix, before closing.   Thanks.
