### ISSUE TITLE
[BUG] The connector will fail if ROOMS=''

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/botkit-starter-rocketchat#11]
For example if you only want the bot to respond to DMs, and not join any rooms.  If the .env is configured with ROOMS='', the connector will fail.

**Comment by arthurTemporim** [comment]
Hi @ear-dev , thank you for the report.
Now the environment variable about `ROOMS` is `ROCKETCHAT_ROOM` following the Rocket.chat pattern:

[.env](https://github.com/RocketChat/botkit-starter-rocketchat/blob/develop/.env)

To make your bot only respond to DM, you just need to let `ROCKETCHAT_ROOM` empty and `RESPOND_TO_DM=true` and don't add the bot to any channel in the Rocket.chat interface.

In the version `0.0.17` this behavior not happen, please test with this version and let me know if this issue remains.

Thank you, very much :smile:
