### ISSUE TITLE
[BUG]   bot invited into public room always reply in #general  (the .env specified room)

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/botkit-starter-rocketchat#3]
Reproduce:

1.  create a new public channel without any users
2.  go into the channel and then `/invite <yourbot>`
3.  start talking to the bot

Trace logs shows that the bot can hear the message, but replies goes to another channel.

**Comment by arthurTemporim** [comment]
This issue was similar to #4 , the solution is in version [0.0.7](https://www.npmjs.com/package/botkit-rocketchat-connector)

**Comment by Sing-Li** [comment]
See #5 - new bug due to fix.

**Comment by diegodorgam** [comment]
working fine now, I think we can close this

**Comment by Sing-Li** [comment]
ok thx
