### ISSUE TITLE
[BUG]  bot invited into private channel does not reply

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/botkit-starter-rocketchat#4]
Steps to reproduce:

1.  create a new private channel with no additional users
2.  enter the channel and invite the bot `/invite <your bot user id>`
3.  talk to the bot

The bot does not reply in the room.    
Trace logs show that the bot did not reply.

**Comment by arthurTemporim** [comment]
The bot was configurated to answer just in the GENERAL room. Now the bot get the room ID where it is added and just see the messages where it is in. I alredy published the solution in the version [0.0.7](https://www.npmjs.com/package/botkit-rocketchat-connector)

**Comment by Sing-Li** [comment]
See #5 - new bugs due to fix.

**Comment by diegodorgam** [comment]
tried this, is working for me, can we close this?

**Comment by Sing-Li** [comment]
yes.  thx
